// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDUCKAVZ7_WFzo1elwr7jdoor6S6Ht_U',
    appId: '1:1096438738821:web:3c7e169e1ac661b767deec',
    messagingSenderId: '1096438738821',
    projectId: 'quiz-app-eaf96',
    authDomain: 'quiz-app-eaf96.firebaseapp.com',
    storageBucket: 'quiz-app-eaf96.firebasestorage.app',
    measurementId: 'G-H8ZZ8X7YG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0AXuOLsIJbAnfzc3iZZ2V9WCrLt6htzg',
    appId: '1:1096438738821:android:dcb40d188940e36d67deec',
    messagingSenderId: '1096438738821',
    projectId: 'quiz-app-eaf96',
    storageBucket: 'quiz-app-eaf96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf0Pvv9Qdu1C2tSKaXKf5YuI8_9GQ4dbs',
    appId: '1:1096438738821:ios:b5185d0b6d954b5467deec',
    messagingSenderId: '1096438738821',
    projectId: 'quiz-app-eaf96',
    storageBucket: 'quiz-app-eaf96.firebasestorage.app',
    iosClientId: '1096438738821-aoi37sctn4gpllri4ijp9s7tu2hm7ndv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf0Pvv9Qdu1C2tSKaXKf5YuI8_9GQ4dbs',
    appId: '1:1096438738821:ios:b5185d0b6d954b5467deec',
    messagingSenderId: '1096438738821',
    projectId: 'quiz-app-eaf96',
    storageBucket: 'quiz-app-eaf96.firebasestorage.app',
    iosClientId: '1096438738821-aoi37sctn4gpllri4ijp9s7tu2hm7ndv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbDUCKAVZ7_WFzo1elwr7jdoor6S6Ht_U',
    appId: '1:1096438738821:web:7b995bf9439f460167deec',
    messagingSenderId: '1096438738821',
    projectId: 'quiz-app-eaf96',
    authDomain: 'quiz-app-eaf96.firebaseapp.com',
    storageBucket: 'quiz-app-eaf96.firebasestorage.app',
    measurementId: 'G-XVYK7NQVL8',
  );
}
